# Generated by Django 5.1.2 on 2024-10-21 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
    ]
